### ISSUE TITLE
Large Photo

### ISSUE THREAD

**Issue by marweil** [GiantMolecularCloud/my-resume#13]
Hi, thanks for this super nice template!

I would like to to put a rectangular foto with full header height in the top right corner. (no grey margins around it) is that possible? thanks!

**Comment by GiantMolecularCloud** [comment]
Thanks and sorry for the late reply.
Having the foto without margins required some work and I could not get perfect alignment. A small vertical offset remained that I had to manually fine-tune. Since the photo size is given by the header height in this particular scenario, I misused the photo size parameter of `\photo` for manual fine-tuning.

These changes are hacky and probably shouldn't go in the main branch, so (for now) they live in the large-photo branch:
https://github.com/GiantMolecularCloud/my-resume/tree/large-photo
