### ISSUE TITLE
problem with page layout with large amount of items

### ISSUE THREAD

**Issue by TEU13** [GiantMolecularCloud/my-resume#15]
Hi When I add a couple of experiences or education. The whole page moves to the 2nd page, including the side bar. The first page only shows the header.

How can I change the layout so the page breaks in the middle of the main bar is not affecting the highlight bar?

[my_resume_with large amount experience.pdf](https://github.com/GiantMolecularCloud/my-resume/files/9415097/my_resume_with.large.amount.experience.pdf)

**Comment by gsnerf** [comment]
I had the same issue. The `highlightbar` and `mainbar` are apparently designed to contain stuff for only one page. The simplest solution would be to move the "too much" content to the `mainbar` of the next page.

This is what a new page looks like in the example:
```tex
\clearpage

\pagestyle{highlightmain}
\highlightbar{}
\mainbar{}
\makebody
```

**Comment by GiantMolecularCloud** [comment]
The template was indeed designed with short documents in mind. Technically, the different parts of a page are constructed with minipages, so overflowing of content to the next page is not possible.
My intended solution was to manually distribute content across pages since it is much easier than redesigning the template with proper page wrapping. The way you would do this is exactly like @gsnerf described.
Sorry if this is an unsatisfying "solution".
